name: Deploy Changed Lambda Functions

on:
  push:
    paths:
      - "backend/lambdas/**"

jobs:
  detect-and-deploy:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.find-lambdas.outputs.matrix }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for accurate diff

      - name: Find changed Lambda folders
        id: find-lambdas
        run: |
          echo "Detecting changed Lambda directories..."


          BASE_REF="${{ github.event.before }}"
          if [ -z "$BASE_REF" ]; then
            if git rev-parse HEAD~1 >/dev/null 2>&1; then
              BASE_REF=$(git rev-parse HEAD~1)
            else
              # Fallback: Use the first commit as base, or skip
              BASE_REF=$(git rev-list --max-parents=0 HEAD)
            fi
          fi

          # Find changed Lambda directories
          changed_dirs=$(git diff --name-only "$BASE_REF" ${{ github.sha }} | grep '^backend/lambdas/' | cut -d '/' -f3 | sort -u)

          if [ -z "$changed_dirs" ]; then
            echo "No Lambda changes detected."
            echo "matrix={\"lambda\":[]}" >> $GITHUB_OUTPUT
          else
            changed_json=$(printf '%s\n' $changed_dirs | jq -R . | jq -s -c .)
            echo "Changed Lambda directories: $changed_json"
            echo "matrix={\"lambda\": $changed_json}" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: detect-and-deploy
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect-and-deploy.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create zip directory
        run: mkdir -p backend/dist

      - name: Zip Lambda code
        run: |
          cd backend/lambdas/${{ matrix.lambda }}
          zip -r ../../dist/${{ matrix.lambda }}.zip . -x "*.pyc" "__pycache__/*"

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ matrix.lambda }} \
            --zip-file fileb://backend/dist/${{ matrix.lambda }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2
